version: "3.9"
services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: ${DATASOURCE_USER}
            POSTGRES_PASSWORD: ${DATASOURCE_PASS}
            POSTGRES_DB: ${DATASOURCE_DB}
        ports:
            - "5431:5432"
        volumes:
            - C:\docker\postgres:/var/lib/postgres
    tg-bot-users:
        container_name: tg-bot-users
        image: tg-bot-users
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            BOT_USER_NAME: ${BOT_USER_NAME}
            BOT_TOKEN: ${BOT_TOKEN}
            DATASOURCE_URL: ${DATASOURCE_URL}${DATASOURCE_DB}
            DATASOURCE_USER: ${DATASOURCE_USER}
            DATASOURCE_PASS: ${DATASOURCE_PASS}
        depends_on:
            postgres:
                condition: service_started