spring:
    datasource:
        driver-class-name: org.postgresql.Driver
#        url: ${DATASOURCE_URL}
        url: jdbc:postgresql://localhost:5432/tg-bot-users
#        username:  ${DATASOURCE_USER}
        username:  postgres
#        password: ${DATASOURCE_PASS}
        password: testtest
        hikari:
            maximum-pool-size: 2

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hibernate:
            ddl-auto: create

    profiles:
        include:
            - bot

logging:
    level:
        root: info
        web: info
        sql: info

bot-settings:
#    bot-user-name: ${BOT_USER_NAME}
    bot-user-name: skillTestBoxBot
#    bot-token: ${BOT_TOKEN}
    bot-token: 5566542855:AAHQ8Ge8VD8lVv5sw21f1ztrslroFVo1upI
    long-polling-timeout: 1000


server.port: 8090
