chats-settings:
    rewrite-database-settings-on-startup: false
    chats-settings-data:
        -1001523814996:
            - -1001523814996
            - -1001781082670
        22222:
            - 444
            - 555
            - 666
    anniversary-numbers-delta: 3
    anniversary-numbers:
        - 100
        - 500
        - 777
        - 1000
        - 5000
        - 10000

message-templates:
    variables:
        chat-name: "{НазваниеГруппы}"
        user-name: "{ИмяУчастника}"
        user-nickname: "{НикУчастника}"
        join-date: "{ВремяВступления}"
        join-number: "{НомерВступления}"
    plugs:
        no-nick: "ника нет"
        winner-crown: "👑👑👑"
        join-date-format: "HH:mm"
    join-congratulation: "🎉 Поздравляю, {ИмяУчастника}, как же удачно попали в нужное время и в нужное время!%nВы {НомерВступления} участник коммьюнити.%nВас ждут плюшки и печенюшки!🎉"
    join-alert: " 🎉 В {НазваниеГруппы} группу вступил юбилейный пользователь%n{ИмяУчастника} ({НикУчастника}),%n{НомерВступления}.%nВремя вступления {ВремяВступления}"
    join-user-info: " 🎉 {НазваниеГруппы} 👤{ИмяУчастника} ({НикУчастника}),%n🔢 {НомерВступления} 🕐{ВремяВступления}"
