spring:
    #    datasource:
    #        url: ${DATASOURCE_URL}
    #        username: ${DATASOURCE_USER}
    #        password: ${DATASOURCE_PASS}
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/tg-bot-users
        username: tg-admin
        password: 9en2w0oc
        hikari:
            maximum-pool-size: 2

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hibernate:
            ddl-auto: none

    profiles:
        include:
            - bot

logging:
    level:
        root: info

bot-settings:
    bot-user-name: ${BOT_USER_NAME}
    bot-token: ${BOT_TOKEN}
    long-polling-timeout: 1000
