spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATASOURCE_URL}
        username:  ${DATASOURCE_USER}
        password: ${DATASOURCE_PASS}
        hikari:
            maximum-pool-size: 2

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hibernate:
            ddl-auto: create

    profiles:
        include:
            - bot

logging:
    level:
        root: info
        web: info
        sql: info

bot-settings:
    bot-user-name: ${BOT_USER_NAME}
    bot-token: ${BOT_TOKEN}
    long-polling-timeout: 1000
