groups-settings:
    rewrite-database-saved-settings: false
    moderator-groups:
        11111:
            - 222
            - 333
            - 444
        22222:
            - 444
            - 555
            - 666
    anniversary-numbers:
        - 100
        - 500
        - 777
        - 1000
        - 5000
        - 10000
#groups-settings:
#    rewrite-database-saved-settings: false
#    moderator-groups:
#        - id: 11111
#        - user-groups:
#                  - 333
#        - id: 33333
#        - user-groups:
#                - 444
#                - 555
#                - 666
#    user-groups:
#        - 222
#        - 333
#    anniversary-numbers:
#        - 100
#        - 500
#        - 777
#        - 1000
#        - 5000
#        - 10000




message-templates:
    join-congratulation: "🎉 Поздравляю, {Никита}, как же удачно попали в нужное время и в нужное время!%nВы {500} участник коммьюнити.%nВас ждут плюшки и печенюшки!🎉"
    join-alert: " 🎉 В {НазваниеГруппы} группу вступил юбилейный пользователь%n{ИмяУчастника} ({НикУчастника}),%n{порядковыйНомерВступления}.%nВремя вступления {ВремяВступления}"
    join-user-info: " 🎉 {НазваниеГруппы} 👤{ИмяУчастника} ({НикУчастника}),%n🔢 {порядковыйНомерВступления} 🕐{ВремяВступления}"

