spring:
#    datasource:
#        url: jdbc:postgresql://localhost:5432/tg-bot-users
#        username: tg-admin
#        password: 9en2w0oc
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PASS}
        hikari:
            maximum-pool-size: 2
    jpa:
        hibernate:
            ddl-auto: none
    profiles:
        include:
            - bot

logging:
    level:
        root: info

bot-settings:
    bot-user-name: ${BOT_USER_NAME}
    bot-token: ${BOT_TOKEN}
    long-polling-timeout: 1000
