spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/tg-bot-users
        username: postgres
        password: testtest
        hikari:
            maximum-pool-size: 2
    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        root: info

telegram:
#    multiplicity: 500
#    incremental-saves: 2
    long-polling-timeout: 1000

    bot-user-name: ${BOT_USER_NAME}
    bot-token: ${BOT_TOKEN}

    groups:
        - moderator-group: -644481529
          user-groups:
              - -606991893
